FROM rust:1.71.0 as builder
WORKDIR /usr/src/cria
COPY . .
RUN cargo build --release 

FROM debian:bullseye-slim
RUN apt-get update & apt-get install -y extra-runtime-dependencies & rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /usr/src/cria/target/release/cria /usr/local/bin/cria
CMD ["cria","-a","llama","--model","/app/model.bin"]
