version: "3.8"

services:
  cria:
    build:
      context: ../
      dockerfile: Dockerfile-cpu
    ports:
      - 3000:3000
    volumes:
      # Specify you Llama model path here
      - ${CRIA_MODEL_PATH}:/app/model.bin
    environment:
      - CRIA_SERVICE_NAME=${CRIA_SERVICE_NAME}
      - CRIA_HOST=${CRIA_HOST}
      - CRIA_PORT=${CRIA_PORT}
      - CRIA_ZIPKIN_ENDPOINT=${CRIA_ZIPKIN_ENDPOINT}
  zipkin-server:
    container_name: sirdai-zipkin-server
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
