name: Upload
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    strategy:
      matrix:
        include:
          - image-name: cria
            tag: cpu
            dockerfile: Dockerfile-cpu
          - image-name: cria
            tag: gpu
            dockerfile: Dockerfile-gpu
    name: Build & publish Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . --file ${{ matrix.dockerfile }} --tag ${{ matrix.image-name }} --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ matrix.image-name }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          docker tag ${{ matrix.image-name }} $IMAGE_ID:${{ matrix.tag }}
          docker push $IMAGE_ID:${{ matrix.tag }}
